# Generated by Django 2.0 on 2018-09-03 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.AutoField(db_column='CG_ML_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='CG_ML_NAME', max_length=255)),
                ('description', models.TextField(db_column='CG_ML_DESC', null=True)),
                ('creation_date', models.DateField(db_column='CG_ML_CREATION_DATE')),
                ('modification_date', models.DateField(db_column='CG_ML_MODIFICATION_DATE', null=True)),
                ('type_of_list', models.CharField(choices=[('Public', 'Public'), ('Shared', 'Shared')], db_column='CG_ML_TYPE', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], db_column='CG_ML_STATUS', max_length=20)),
                ('creator', models.ForeignKey(db_column='CG_ML_CREATOR_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailing_list_creator', to=settings.AUTH_USER_MODEL)),
                ('modifier', models.ForeignKey(db_column='CG_ML_MODIFIER_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailing_list_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CM_Mailing_list_tbl',
            },
        ),
        migrations.CreateModel(
            name='MailingListCustomerUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails', models.TextField(db_column='CG_ML_CU_EMAILS', null=True)),
                ('list_id', models.ForeignKey(db_column='CG_ML_CU_ID', on_delete=django.db.models.deletion.CASCADE, to='mailing_list.MailingList')),
            ],
            options={
                'db_table': 'CM_Mailing_list_custupl_tbl',
            },
        ),
        migrations.CreateModel(
            name='MailingListUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('Public', 'Public'), ('Shared', 'Shared')], max_length=20)),
                ('mailing_list', models.ForeignKey(db_column='CG_ML_ID', on_delete=django.db.models.deletion.CASCADE, to='mailing_list.MailingList')),
                ('mailing_user', models.ForeignKey(db_column='CG_ML_USER_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CM_Mailing_list_usr_tbl',
            },
        ),
    ]
