# Generated by Django 2.0 on 2018-09-04 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingListSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(db_column='CG_ML_STP_PARAMETER', max_length=255)),
                ('value', models.CharField(db_column='CG_ML_STP_VALUE', max_length=500, null=True)),
                ('inclusion_flag', models.BooleanField(db_column='CG_ML_STP_INC_FLG', default=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=20, null=True)),
                ('mailing_list', models.ForeignKey(db_column='CG_ML_STP_ID', on_delete=django.db.models.deletion.CASCADE, to='mailing_list.MailingList')),
            ],
        ),
    ]
