# Generated by Django 2.0 on 2018-09-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_list', '0002_mailinglistsetup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglistsetup',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], db_column='CG_ML_STATUS', max_length=20, null=True),
        ),
        migrations.AlterModelTable(
            name='mailinglistsetup',
            table='CM_Mail_list__Setup_tbl',
        ),
    ]
