# Generated by Django 2.0 on 2018-08-20 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('test_permission_3', 'To provide AC-Bus facility'),)},
        ),
    ]
