# Generated by Django 2.0.7 on 2018-08-21 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180820_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('test_permission', 'To provide view facility'), ('test_permission_3', 'Cannot view'))},
        ),
    ]
