# Generated by Django 2.0.7 on 2018-08-23 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
