# Generated by Django 2.0 on 2018-09-05 06:06

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('users', '0010_remove_user_is_superuser'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='permissions',
            table='CM_permission_tbl',
        ),
        migrations.AlterModelTable(
            name='rolespermissions',
            table='CM_role_perm_mapping_tbl',
        ),
        migrations.AlterModelTable(
            name='user',
            table='CM_User_Prfl_tbl',
        ),
        migrations.AlterModelTable(
            name='usersroles',
            table='CM_User_roles_mapping_tbl',
        ),
    ]
