# Generated by Django 2.0 on 2018-09-03 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(db_column='CG_MT_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='CG_MT_NAME', max_length=255)),
                ('description', models.TextField(db_column='CG_MT_DESC', null=True)),
                ('creation_date', models.DateField(db_column='CG_MT_CREATION_DATE')),
                ('modification_date', models.DateField(db_column='CG_MT_MODIFICATION_DATE', null=True)),
                ('type_of_template', models.CharField(choices=[('Public', 'Public'), ('Shared', 'Shared')], db_column='CG_MT_TYPE', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], db_column='CG_MT_STATUS', max_length=20)),
                ('creator', models.ForeignKey(db_column='CG_MT_CREATOR_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_creator', to=settings.AUTH_USER_MODEL)),
                ('modifier', models.ForeignKey(db_column='CG_MT_MODIFIER_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CM_Template_tbl',
            },
        ),
        migrations.CreateModel(
            name='TemplateBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(db_column='CG_MT_BODY')),
                ('template', models.ForeignKey(db_column='CG_MT_ID', on_delete=django.db.models.deletion.CASCADE, to='mailing_templates.Template')),
            ],
            options={
                'db_table': 'CM_Template_body_tbl',
            },
        ),
        migrations.CreateModel(
            name='TemplateUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_template', models.CharField(choices=[('Public', 'Public'), ('Shared', 'Shared')], db_column='CG_MT_TYPE', max_length=20)),
                ('template', models.ForeignKey(db_column='CG_MT_ID', on_delete=django.db.models.deletion.CASCADE, to='mailing_templates.Template')),
                ('user', models.ForeignKey(db_column='CG_MT_USER_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
